### ISSUE TITLE
Regulation creation and deprecation must be broadcasted to all parties

### ISSUE THREAD

**Issue by alzoubi36** [DLT-EarlyBirds/it-compliance#53]
Currently only the Supervisory Authority sees created and deprecated regulations

**Comment by ValiHar** [comment]
This is already happening implicitly. The regulation linear ID is passed to each of its rules on creation to create a linear pointer. As the linear pointer is dereferencend during transaction creation to create a reference state as an input state for the transaction, the regulation is distributed to all parties getting the rule, meaning to all parties in the network. 

If a regulation without any rules exists, then it is not broadcasted, but it is also not relevant.

**Comment by alzoubi36** [comment]
Cool. But I don't think a FSP should wait until creating a ClaimTemplateSuggestion or a SpecificClaim to be able to see a Regulation. Maybe the creation of a regulation happens some time before the creation of its rules. In this case the FSPs still need to see the regulation when it's released. I'll reopen the issue.
